<?php
namespace App\Commands;


use Jan\Component\Console\Command\Command;
use Jan\Component\Console\Input\InputInterface;
use Jan\Component\Console\Output\OutputInterface;



/**
 * Class SayHelloCommand
 * @package App\Commands
 *
 *  php console make:command SayHelloCommand
 * <Generated By JanFramework>
*/
class SayHelloCommand extends Command
{

    /** @var string  */
    protected $name = 'say:hello';


    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return mixed|void
    */
    public function execute(InputInterface $input, OutputInterface $output)
    {
           // put some logic here
    }
}